---

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    mode: 0644
    owner: root
    group: root
  notify:
  - restart sshd
  become: true

- name: Disable IPv6 all
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true

- name: Disable IPv6 default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true

- name: Disable IPv6 lo
  ansible.posix.sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true